version: '3'

networks:
  oracle_oraclenet:
    external: true
    
services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:7.0.0.132
    container_name: kwsnet-onlyoffice
    restart: always
    deploy:
        resources:
            limits:
              memory: 2048M
    networks:
      - oracle_oraclenet
    env_file:
      - .env
    volumes:
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/lib:/var/lib/onlyoffice
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/db:/var/lib/postgresql
