version: '3'

networks:
  infra_chatbot:
    external: true
    
services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    container_name: kwsnet-onlyoffice
    restart: always
    deploy:
        resources:
            limits:
              memory: 2048M
    networks:
      - infra_chatbot
    env_file:
      - .env
    volumes:
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/lib:/var/lib/onlyoffice
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/db:/var/lib/postgresql
